name:               modernmapmerge
version:            0.2.0.0
license:            BSD3
author:             "James Cranch"
maintainer:         "j.d.cranch@sheffield.ac.uk"
copyright:          "2022-23 James Cranch (all), 2020 Fumiaki Kinoshita (mini-witherable)"
synopsis:           Proof-of-concept for improved merges in Haskell
category:           Data structures

dependencies:
  - base                        >= 4.15         && < 4.19
  - containers                  >= 0.6.4.1      && < 0.7
  - indexed-traversable         >= 0.1.2        && < 0.2

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror
  - -Wwarn=missing-home-modules
  - -O2

library:
  source-dirs:      src-modernmapmerge
  dependencies:
    - witherable                      >= 0.4.2    && < 0.5

internal-libraries:

  listmap:
    source-dirs:    src-listmap
    dependencies:
      - modernmapmerge
      - witherable                    >= 0.4.2    && < 0.5

  maplike:
    source-dirs:    src-maplike
    dependencies:
      - modernmapmerge
      - witherable                    >= 0.4.2    && < 0.5

  extra:
    source-dirs:    src-extra
    dependencies:
      - modernmapmerge
      - array                         >= 0.5.4.0  && < 0.6
      - bytestring                    >= 0.11.3   && < 0.12
      - bytestring-trie               >= 0.2.7    && < 0.3
      - data-default                  >= 0.7.1.1  && < 0.8
      - hashable                      >= 1.3.5    && < 1.5
      - indexed-traversable-instances >= 0.1.1    && < 0.2
      - transformers                  >= 0.5.6.2  && < 0.7
      - unordered-containers          >= 0.2.16   && < 0.3
      - vector                        >= 0.12.3.1 && < 0.14
      - witherable                    >= 0.4.2    && < 0.5
    ghc-options:
      - -fno-warn-orphans

tests:
  test-maplike:
    main:                Spec.hs
    source-dirs:         test-maplike
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec                          >= 2.11     && < 2.12
    - maplike
    build-tool-depends:
    - hspec-discover:hspec-discover  >= 2.11     && < 2.12
